"""GENERATED by scripts/codegen_quiz_families.py. DO NOT EDIT.

The first-run quiz: eight drink families a person can answer about instantly, and the
STYLE_PRIOR flavour vector each one stands for. See the generator for why these eight.
"""

from __future__ import annotations

#: family -> (what the quiz calls it, category, confidence, axes)
QUIZ_DRINKS: dict[str, tuple[str, str, float, dict[str, float]]] = {
    "ipa": (
        "IPA",
        "beer",
        0.35,
        {
            "bitterness": 0.75,
            "body_fullness": 0.4,
            "carbonation": 0.5,
            "citrus": 0.65,
            "dryness_finish": 0.55,
            "grassy": 0.3,
            "malty_bready": 0.35,
            "piney_resinous": 0.55,
            "tropical": 0.5,
        },
    ),
    "lager": (
        "Lager",
        "beer",
        0.35,
        {
            "bitterness": 0.3,
            "body_fullness": 0.3,
            "carbonation": 0.6,
            "dryness_finish": 0.5,
            "grassy": 0.3,
            "malty_bready": 0.4,
        },
    ),
    "stout": (
        "Stout",
        "beer",
        0.35,
        {
            "bitterness": 0.5,
            "body_fullness": 0.7,
            "caramel_toffee": 0.45,
            "carbonation": 0.4,
            "malty_bready": 0.5,
            "nutty": 0.35,
            "roasted_coffee_choc": 0.85,
            "sweet": 0.35,
        },
    ),
    "wheat": (
        "Wheat beer",
        "beer",
        0.35,
        {
            "banana_ester": 0.7,
            "body_fullness": 0.45,
            "carbonation": 0.6,
            "citrus": 0.4,
            "floral": 0.3,
            "malty_bready": 0.4,
            "spicy_phenolic": 0.55,
            "sweet": 0.3,
        },
    ),
    "bourbon": (
        "Bourbon",
        "spirit",
        0.35,
        {
            "alcohol_warmth": 0.75,
            "caramel_toffee": 0.6,
            "honey": 0.4,
            "nutty": 0.35,
            "roasted_coffee_choc": 0.3,
            "spicy_phenolic": 0.3,
            "sweet": 0.45,
            "vanilla_oak": 0.75,
        },
    ),
    "gin": (
        "Gin",
        "spirit",
        0.35,
        {
            "alcohol_warmth": 0.6,
            "citrus": 0.45,
            "dryness_finish": 0.6,
            "floral": 0.5,
            "grassy": 0.3,
            "herbal": 0.7,
            "piney_resinous": 0.45,
            "spicy_phenolic": 0.35,
        },
    ),
    "vodka": (
        "Vodka",
        "spirit",
        0.35,
        {
            "alcohol_warmth": 0.7,
            "dryness_finish": 0.6,
            "sweet": 0.1,
        },
    ),
    "agave": (
        "Tequila",
        "spirit",
        0.35,
        {
            "alcohol_warmth": 0.7,
            "citrus": 0.4,
            "dryness_finish": 0.55,
            "floral": 0.3,
            "grassy": 0.35,
            "herbal": 0.55,
            "spicy_phenolic": 0.4,
        },
    ),
}

#: The order the quiz asks in — beer first, then spirits.
QUIZ_ORDER: tuple[str, ...] = (
    "ipa",
    "lager",
    "stout",
    "wheat",
    "bourbon",
    "gin",
    "vodka",
    "agave",
)
