"""GENERATE packages/schema/bcd_schema/quiz.py — the first-run quiz's eight drinks.

A drinker who has rated nothing has no profile, so there is nothing to recommend from and
nothing personal to put on a product's screen. The quiz is the smallest thing that fixes
that: eight drink families, answered in about twenty seconds, folded into exactly the same
`build_profile` pipeline a real rating goes through.

Which eight was measured rather than chosen. Every family has a flavour centroid and they
are genuinely distinct (median cosine 0.441 across the 231 pairs), so the question is which
subset spans the space. A greedy max-spread pick over the live catalog gives gin, porter,
sour, brandy, wheat, ipa, sake and rye -- flavour-optimal and a strange thing to ask a
person on their first run, since it never mentions lager, bourbon or vodka. The familiar
eight below cover 0.872 of the same space against that set's 0.875, so asking about drinks
people actually recognise costs three thousandths of nothing (2026-10-02).

The vectors are the STYLE_PRIOR vectors the catalog's own 507k style-filed products carry,
so a quiz answer puts the drinker in the same space their ratings later will. They are
generated here rather than computed at runtime because `bcd_enrich` is not on the API's
import path; `tests/test_quiz.py` regenerates and compares, so this cannot drift silently.

    .venv/bin/python scripts/codegen_quiz_families.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for p in ("packages/schema", "services/enrich"):
    sys.path.insert(0, str(ROOT / p))

from bcd_enrich.style_prior import sensory_from_style  # noqa: E402
from bcd_schema import Category  # noqa: E402

#: family, the style the vector is taken from, its category, and what the quiz calls it.
#: The prompt is the drink as a person would say it, not as the catalog files it.
QUIZ_FAMILIES: tuple[tuple[str, str, Category, str], ...] = (
    ("ipa", "IPA", Category.BEER, "IPA"),
    ("lager", "Lager", Category.BEER, "Lager"),
    ("stout", "Stout", Category.BEER, "Stout"),
    ("wheat", "Hefeweizen", Category.BEER, "Wheat beer"),
    ("bourbon", "Bourbon", Category.SPIRIT, "Bourbon"),
    ("gin", "Gin", Category.SPIRIT, "Gin"),
    ("vodka", "Vodka", Category.SPIRIT, "Vodka"),
    ("agave", "Tequila", Category.SPIRIT, "Tequila"),
)

HEADER = '''"""GENERATED by scripts/codegen_quiz_families.py. DO NOT EDIT.

The first-run quiz: eight drink families a person can answer about instantly, and the
STYLE_PRIOR flavour vector each one stands for. See the generator for why these eight.
"""

from __future__ import annotations

'''


def main() -> None:
    rows = []
    for family, style, category, prompt in QUIZ_FAMILIES:
        sv = sensory_from_style(style, category, style_hint=style)
        if sv is None:
            raise SystemExit(f"no style-prior vector for {style!r} — the quiz cannot name it")
        axes = {k: round(float(v), 4) for k, v in sorted(sv.axes.items()) if v}
        rows.append((family, prompt, category.value, round(float(sv.confidence), 3), axes))

    out = [HEADER, "#: family -> (what the quiz calls it, category, confidence, axes)\n",
           "QUIZ_DRINKS: dict[str, tuple[str, str, float, dict[str, float]]] = {\n"]
    for family, prompt, cat, conf, axes in rows:
        out.append(f'    "{family}": (\n        "{prompt}",\n        "{cat}",\n'
                   f"        {conf},\n        {{\n")
        for k, v in axes.items():
            out.append(f'            "{k}": {v},\n')
        out.append("        },\n    ),\n")
    out.append("}\n\n")
    out.append("#: The order the quiz asks in — beer first, then spirits.\n")
    out.append("QUIZ_ORDER: tuple[str, ...] = (\n")
    for family, *_ in rows:
        out.append(f'    "{family}",\n')
    out.append(")\n")

    dest = ROOT / "packages/schema/bcd_schema/quiz.py"
    dest.write_text("".join(out))
    print(f"generated {len(rows)} quiz drinks -> {dest.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
