#!/usr/bin/env python3
"""Codegen telemetry bindings from telemetry/events.yaml — the single source of truth.

Emits:
  - ios/BCDKit/Sources/BCDKit/Generated/TelemetryEvents.swift  (Swift enum + tiers)
  - services/telemetry/bcd_telemetry/generated_events.py        (Python allowlist)

`make codegen && git diff --exit-code` proves the two are generated, not hand-drifted.
Both files carry a DO-NOT-EDIT banner.
"""

from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(__file__)
SPEC = os.path.normpath(os.path.join(HERE, "..", "telemetry", "events.yaml"))
SWIFT_OUT = os.path.normpath(os.path.join(
    HERE, "..", "ios", "BCDKit", "Sources", "BCDKit", "Generated", "TelemetryEvents.swift"))
PY_OUT = os.path.normpath(os.path.join(
    HERE, "..", "services", "telemetry", "bcd_telemetry", "generated_events.py"))

BANNER = "GENERATED by scripts/codegen_events.py from telemetry/events.yaml. DO NOT EDIT."


def _camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def gen_swift(spec: dict) -> str:
    lines = [
        f"// {BANNER}",
        "import Foundation",
        "",
        "/// Every telemetry event name, with its required consent tier. The client can only",
        "/// emit events that exist here, so the warehouse schema and the app never drift.",
        "public enum TelemetryEvent: String, Sendable, CaseIterable {",
    ]
    for ev in spec["events"]:
        lines.append(f'    case {_camel(ev["name"])} = "{ev["name"]}"')
    lines += ["", "    public var tier: ConsentTier {", "        switch self {"]
    for ev in spec["events"]:
        tier = ev["tier"]
        tier_case = {"analytics": "analytics", "personalization": "personalization",
                     "data_sharing": "dataSharing"}[tier]
        lines.append(f"        case .{_camel(ev['name'])}: return .{tier_case}")
    lines += ["        }", "    }", "}", ""]
    return "\n".join(lines)


def gen_python(spec: dict) -> str:
    names = [ev["name"] for ev in spec["events"]]
    tiers = {ev["name"]: ev["tier"] for ev in spec["events"]}
    lines = [
        f'"""{BANNER}"""',
        "",
        "from __future__ import annotations",
        "",
        "# The allowlist the collector validates against. Unknown events are rejected.",
        "EVENT_NAMES: frozenset[str] = frozenset({",
    ]
    for n in names:
        lines.append(f'    "{n}",')
    lines += ["})", "", "EVENT_TIERS: dict[str, str] = {"]
    for n in names:
        lines.append(f'    "{n}": "{tiers[n]}",')
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    with open(SPEC, encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    os.makedirs(os.path.dirname(SWIFT_OUT), exist_ok=True)
    os.makedirs(os.path.dirname(PY_OUT), exist_ok=True)
    with open(SWIFT_OUT, "w", encoding="utf-8") as f:
        f.write(gen_swift(spec))
    with open(PY_OUT, "w", encoding="utf-8") as f:
        f.write(gen_python(spec))
    print(f"generated {len(spec['events'])} events ->")
    print(f"  {os.path.relpath(SWIFT_OUT)}")
    print(f"  {os.path.relpath(PY_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
