"""GENERATED by scripts/codegen_events.py from telemetry/events.yaml. DO NOT EDIT."""

from __future__ import annotations

# The allowlist the collector validates against. Unknown events are rejected.
EVENT_NAMES: frozenset[str] = frozenset({
    "session_start",
    "session_end",
    "scan_session_start",
    "scan_frame_batch",
    "scan_candidate_shown",
    "scan_resolved",
    "scan_corrected_by_user",
    "overlay_impression",
    "overlay_tap",
    "product_view",
    "provenance_expanded",
    "rating_submitted",
    "list_add",
    "alert_fired",
    "alert_converted",
    "agent_task_created",
    "agent_task_completed",
    "purchase_intent",
    "paywall_shown",
    "paywall_converted",
    "weekly_profile_delta_shown",
})

EVENT_TIERS: dict[str, str] = {
    "session_start": "analytics",
    "session_end": "analytics",
    "scan_session_start": "analytics",
    "scan_frame_batch": "personalization",
    "scan_candidate_shown": "analytics",
    "scan_resolved": "analytics",
    "scan_corrected_by_user": "personalization",
    "overlay_impression": "analytics",
    "overlay_tap": "analytics",
    "product_view": "analytics",
    "provenance_expanded": "analytics",
    "rating_submitted": "personalization",
    "list_add": "personalization",
    "alert_fired": "analytics",
    "alert_converted": "analytics",
    "agent_task_created": "data_sharing",
    "agent_task_completed": "data_sharing",
    "purchase_intent": "data_sharing",
    "paywall_shown": "analytics",
    "paywall_converted": "analytics",
    "weekly_profile_delta_shown": "personalization",
}
